### ISSUE TITLE
Add time drift and other NTPd metrics

### ISSUE THREAD

**Issue by benjamin-bergia** [joyent/triton-cmon-agent#1]
Related to https://github.com/joyent/sdc-cloud-analytics/issues/2.

We are now using CMON on our environments and I would like to get some basic ntp metrics.
Additionally what is the recommended way to extend the metrics collected ? If possible, there is other metrics that I would like to see and I would be willing to write some scripts myself.

**Comment by dfredell** [comment]
Does this help https://github.com/joyent/triton-cmon-agent/commit/5803926766bcd39eb2aca1d5a11667492a725d3c ?

**Comment by benjamin-bergia** [comment]
That's more than I could have asked for thank you. I will close this one.

**Comment by dfredell** [comment]
PS. I'm not affiliated with Joyent. I just use their products.
