### ISSUE TITLE
cpu usage idle

### ISSUE THREAD

**Issue by benjamin-bergia** [joyent/triton-cmon-agent#2]
Since cmon-agent is already collecting user, system and wait time, could we add the time spent idle ? 

Or is there a reliable way to calculate it from the three previous metrics ?

**Comment by bahamat** [comment]
Filed internally as TRITON-1014

**Comment by khalfella** [comment]
`cpu_idle_seconds_total` and other cpu metrics have been added recently as a part of [TRITON-433](https://github.com/joyent/triton-cmon-agent/commit/5b84b9e14000d72c4fb6b324ada1f5f6aaf36976).
