### ISSUE TITLE
sdc network as a datapoint

### ISSUE THREAD

**Issue by Adel-Magebinary** [joyent/triton-cmon-agent#3]
Hi can you please add network uuid into the data point too? Otherwise, the bandwidth report won't be accurate.

https://github.com/joyent/triton-cmon-agent/blob/584110282ebe342b39aa3c3b612785ff8e43105d/lib/instrumenter/collectors-vm/link.js#L109

Cheers,
Adel.

**Comment by khalfella** [comment]
This is being reviewed in [PR#6](https://github.com/joyent/triton-cmon-agent/pull/6)
